# Generated by Django 4.1.6 on 2023-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
